### ISSUE TITLE
Stats error

### ISSUE THREAD

**Issue by reysonk** [ch3p4ll3/QBittorrentBot#19]
Thank you for your wonderful bot, how to cure the problem?
when entering a command /stats, such an error occurs in the log
```
'coretemp'

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker

    await self.loop.run_in_executor(

  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/app/src/bot.py", line 116, in stats_command

    f"**CPU температура:** {psutil.sensors_temperatures()['coretemp'][0].current}°C\n" \

KeyError: 'coretemp'
```

**Comment by ch3p4ll3** [comment]
@reysonk Hi, what happens if you print psutil.sensors_temperatures()? Maybe you could have different sensor names

**Comment by reysonk** [comment]
nothing happens

![изображение](https://github.com/ch3p4ll3/QBittorrentBot/assets/26927358/ba83f0dd-e3ff-449a-afc9-8a4a0d7ded8e)

**Comment by ch3p4ll3** [comment]
@reysonk sorry, maybe I explained myself wrong. You should open a python terminal, import psutils and then run the command

**Comment by reysonk** [comment]
![IMG_20230801_195655.jpg](https://github.com/ch3p4ll3/QBittorrentBot/assets/26927358/dde1856a-e8fe-492e-b5e8-b61d5cf6263d)

sorry for quality.

**Comment by ch3p4ll3** [comment]
@reysonk Ok, so, replace coretemp with k10temp and you'll be fine

**Comment by reysonk** [comment]
tnx all works nice!

![изображение](https://github.com/ch3p4ll3/QBittorrentBot/assets/26927358/ed63565f-ce29-40c5-b16b-445aee7ff8b2)
