### ISSUE TITLE
Add possibility to translate and sequential order

### ISSUE THREAD

**Issue by DarkAssassinUA** [ch3p4ll3/QBittorrentBot#31]
Hi!
Also can you please and possibility to translate bot buttons(button "Language settings" do nothing) and "download in sequential order" option

**Comment by ch3p4ll3** [comment]
Hi, I'm currently working on [localization](https://github.com/ch3p4ll3/QBittorrentBot/tree/v2-add-localization), when the whole bot is ready it can be translated into other languages.

To help add languages ​​you can do it from the following [link](https://explore.transifex.com/ch3p4ll3/qbittorrentbot/)), but at the moment I won't use it until I finish the bot.

For the other client option I can think about it
